nop:
  debug: true


  server:
    port: 9092

  cluster:
    registration:
      enabled: true

    sentinel:
      flow-rules: |
        [{
          resource: "/graphql",
          grade: 1,
          count: 3
        }]
        

  graphql:
    schema-introspection:
      enabled: true

quarkus:
  http:
    host: 0.0.0.0
    port: ${nop.server.port}